version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-sistemadb
    environment:
      POSTGRES_DB: sistemadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
